name: Generate Name and Save to MongoDB

on:
  workflow_dispatch:
    inputs:
      episode_id:
        description: 'ID for the episode'
        required: true
        default: '123'
      prompt:
        description: 'Speech prompt to synthesize'
        required: true
        default: 'Hello, how are you?'

jobs:
  synthesize_speech:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/toxiguard/text-to-speech/dependency-image:latest

      - name: Run Python script in Docker container
        run: |
            docker run --rm \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e SPEECH_KEY=${{ secrets.SPEECH_KEY }} \
              -e SPEECH_REGION=${{ secrets.SPEECH_REGION }} \
              -e EPISODE_ID=${{ github.event.inputs.episode_id }} \
              -e PROMPT="${{ github.event.inputs.prompt }}" \
              ghcr.io/toxiguard/text-to-speech/dependency-image:latest || echo "Docker container failed to start.


      - name: Show Docker container logs (if any)
        run: |
          CONTAINER_ID=$(docker ps -q)
          if [ -z "$CONTAINER_ID" ]; then
            echo "No containers are running. Logs will not be available."
          else
            echo "Container logs:"
            docker logs $CONTAINER_ID
          fi



